apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  creationTimestamp: null
  name: my-integration
  namespace: default
spec:
  sources:
  - content: "
      import org.apache.camel.builder.RouteBuilder;

      public class Sample extends RouteBuilder {
        @Override
        public void configure() throws Exception {
          from(\"timer:tick\")
          .log(\"Hello Integration!\");
         }
      }"
    name: Sample.java
status: {}
