---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: suite-app
  name: app-mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-mongodb
  template:
    metadata:
      labels:
        app: app-mongodb
    spec:
      automountServiceAccountToken: false
      containers:
        - name: app-mongodb
          image: mongo:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  namespace: suite-app
  name: app-mongo-service
spec:
  selector:
    app: app-mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
